import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillMediumSquare
} from "react-icons/ai";
import {SiHackerrank} from "react-icons/si";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import hazal from "../public/hazal.jpeg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import { FaRegHandSpock } from "react-icons";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.jpeg";
import web3 from "../public/web3.jpeg";
import web4 from "../public/web4.jpeg";
import web5 from "../public/web5.jpeg";
import web6 from "../public/web6.jpeg";
import web7 from "../public/web7.jpeg";
import web8 from "../public/web8.jpeg";
import web9 from "../public/web9.jpeg";
import web10 from "../public/web10.jpeg";
import web11 from "../public/web11.jpeg";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""} >
      <Head>
        <title>Hazal Gültekin Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons lg:text-xl sm:text-sm">Hazal Gültekin</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Hazal Gültekin
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Data Analyst and Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              <span className="block">Hi there 🖐🏽</span> My name is Hazal and I am a 3rd year Computer Engineering student.
              I am trying to improve myself by working in the field of data analyst.
              In this portfolio, I explained in detail how I created a data analysis project and what stages it went through.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/HazalGultekin"><AiFillGithub/></a>
              <a href="https://www.hackerrank.com/hazallgultekin"><SiHackerrank/></a>
              <a href="https://www.linkedin.com/in/hazal-g%C3%BCltekin-7b2607216/"><AiFillLinkedin /></a>
              <a href="https://medium.com/@hazallgultekin"><AiFillMediumSquare/></a>
              <a href="https://twitter.com/home"><AiFillTwitterCircle /> </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={hazal} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
      
        <section className="py-16">
          <div>
            <h3 className="text-4xl justify-center flex font-semibold text-black leading-6 dark:text-gray-200">Data Analyst Portfolio Project - Sales Management</h3>
            <p className="mt-6 text-base justify-center flex  text-black dark:text-gray-200">
              In this project, I used tools such as SQL Server, Excel, AdventureWorks DBs and PowerBI Desktop.  
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
          </div>
        </section>
        <section>
          <div className=" py-10">
              <div className="sm:flex sm:items-center">
                <div className="sm:flex-auto">
                  <h1 className="text-3xl font-semibold text-black leading-6 dark:text-gray-200">Business Request & User Stories</h1>
                  <p className="mt-6 text-base text-black dark:text-gray-200">
                    The business request for this data analyst project was an executive sales report for sales managers. 
                    Based on the request that was made from the business we following user stories were defined to fulfill delivery and ensure that acceptance criteria’s were maintained throughout the project.            
                  </p>
                </div>     
              </div>
              <div className="mt-8 flow-root">
                <div className="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
                  <div className="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                    <table className="min-w-full divide-y divide-gray-700">
                      <thead>
                        <tr>
                          <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-teal-700 sm:pl-0 dark:text-gray-200">
                          As a (role)
                          </th>
                          <th scope="col" className="py-3.5 px-3 text-left text-sm font-semibold text-teal-700 dark:text-gray-200">
                          I want (request / demand)
                          </th>
                          <th scope="col" className="py-3.5 px-3 text-left text-sm font-semibold text-teal-700 dark:text-gray-200">
                          So that I (user value)
                          </th>
                          <th scope="col" className="py-3.5 px-3 text-left text-sm font-semibold text-teal-700 dark:text-gray-200">
                          Acceptance Criteria
                          </th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-800">
                      <tr>
                        <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-600 dark:text-gray-200 sm:pl-0">Sales Manager</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-600 dark:text-gray-200">To get a dashboard overview of internet sales</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-600 dark:text-gray-200">Can follow better which customers and products sells the best</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-600 dark:text-gray-200">A Power BI dashboard which updates data once a day</td>
                      </tr>
                      <tr>
                        <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-600 dark:text-gray-200 sm:pl-0">Sales Representative</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-600 dark:text-gray-200">A detailed overview of Internet Sales per Customers</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-600 dark:text-gray-200">Can follow up my customers that buys the most and who we can sell more to</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-600 dark:text-gray-200">A Power BI dashboard which allows me to filter data for each customer</td>
                      </tr>
                      <tr>
                        <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-600 dark:text-gray-200 sm:pl-0">Sales Representative</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-600 dark:text-gray-200">A detailed overview of Internet Sales per Products</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-600 dark:text-gray-200">Can follow up my Products that sells the most</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-600 dark:text-gray-200">A Power BI dashboard which allows me to filter data for each Product</td>
                      </tr>
                      <tr>
                        <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-600 dark:text-gray-200 sm:pl-0">Sales Manager</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-600 dark:text-gray-200">A dashboard overview of internet sales</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-600 dark:text-gray-200">Follow sales over time against budget</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-600 dark:text-gray-200">A Power Bi dashboard with graphs and KPIs comparing against budget.</td>
                      </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl font-semibold text-black leading-6 dark:text-gray-200">Data Cleansing & Transformation (SQL)</h3>
            <p className="mt-6 text-base text-black dark:text-gray-200">
              To create the necessary data model for doing analysis and fulfilling the business needs defined in the user stories the following tables were extracted using SQL.
              One data source (sales budgets) were provided in Excel format and were connected in the data model in a later step of the process.
              Below are the SQL statements for cleansing and transforming necessary data.            
            </p>
          </div>
          <div className="mt-10 mb-5 ">
            <h3 className="font-bold dark:text-gray-200">DIM_Calendar:</h3>
            <div className="basis-1/3 mt-3 flex-1 border border-gray-300 rounded-lg">
            <Image src={web5} width={500} height={500} />
            </div>
          </div>   
          <div className="mt-10 mb-5 ">
            <h3 className="font-bold dark:text-gray-200">DIM_Customers:</h3>
            <div className="basis-1/3 mt-3 flex-1 border border-gray-300 rounded-lg">
            <Image src={web6} width={500} height={500} />
            <Image src={web7} width={500} height={500} />
            </div>
          </div> 
          <div className="mt-10 mb-5 ">
            <h3 className="font-bold dark:text-gray-200">DIM_Products:</h3>
            <div className="basis-1/3 mt-3 flex-1 border border-gray-300 rounded-lg">
            <Image src={web8} width={500} height={500} />
            <Image src={web9} width={500} height={500} />
            </div>
          </div> 
          <div className="mt-10 mb-5 ">
            <h3 className="font-bold dark:text-gray-200">FACT_InternetSales:</h3>
            <div className="basis-1/3 mt-3 flex-1 border border-gray-300 rounded-lg">
            <Image src={web10} width={500} height={500} />
            <Image src={web11} width={500} height={500} />
            </div>
          </div> 
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl font-semibold text-black leading-6 dark:text-gray-200">Data Model</h3>
            <p className="mt-6 text-base text-black dark:text-gray-200">
              Below is a screenshot of the data model after cleansed and prepared tables were read into Power BI.
              This data model also shows how FACT_Budget hsa been connected to FACT_InternetSales and other necessary DIM tables.            
            </p>
          </div>
          <div className="mt-10 mb-5 ">
            <div className="basis-1/3 mt-3 flex-1">
            <Image src={web2} width={"100%"}
                height={"100%"} />
            </div>
          </div> 
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl font-semibold text-black leading-6 dark:text-gray-200">Sales Management Dashboard</h3>
            <p className="mt-6 text-base text-black dark:text-gray-200">
              The finished sales management dashboard with one page with works as a dashboard and overview, with two other pages focused on combining tables for necessary details and visualizations to show sales over time, per customers and per products.          
            </p>
          </div>
          <div className="mt-10 mb-5 ">
            <div className="basis-1/3 mt-3 flex-1">
            <Image src={web1} width={"100%"}
                height={"100%"} />
            </div>
          </div> 
        </section>
      </main>
    </div>
  );
}